### ISSUE TITLE
Incorrect Pulse Length

### ISSUE THREAD

**Issue by FaustoMendezcom** [Zepheus/ESP8266-rf-mqtt-bridge#1]
Incorrect Pulse Length (Nodemcu)
Fix:
mySwitch.setProtocol(protocol,pulselen);
insted of:
        mySwitch.setPulseLength(pulselen);
        mySwitch.setProtocol(protocol);

**Comment by Zepheus** [comment]
Hi Fausto,

You are correct! I will push this fix as soon as possible, or in the meantime feel free to submit a pull request yourself.

**Comment by Zepheus** [comment]
Fixed in ede83d4f3db24b5b0968dbf367a4e724111d7837
