### ISSUE TITLE
simply put the static IP or hostname of your MQTT broker in the hostString variable.

### ISSUE THREAD

**Issue by prasad7676** [Zepheus/ESP8266-rf-mqtt-bridge#3]
Im trying to find in code to put static ip but can't find out could you pls help me?

**Comment by Zepheus** [comment]
Hi,

You should be able to set the IP and port directly here:
https://github.com/Zepheus/ESP8266-rf-mqtt-bridge/blob/ede83d4f3db24b5b0968dbf367a4e724111d7837/bridge.ino#L40

and skip the `find_raspberry` call. 

Here's an example from the PubSubClient library:
https://github.com/knolleary/pubsubclient/blob/dddfffbe0c497073d960f3b9f83c8400dc8cad6d/examples/mqtt_esp8266/mqtt_esp8266.ino#L112

Does that answer your question?

**Comment by jesperuk** [comment]
Hi Zepheus,

trying to set the static brokerIp i get "too many decimal points in number"

**Comment by Landrash** [comment]
@jesperuk Paste a copy of what you have entered. (Change the IP to something else but keep the formatting the same)

**Comment by Zepheus** [comment]
@jesperuk Since there hasn't been any activity on this issue I'm closing it.
Feel free to reopen if you need more help.
